
exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"


# Site settings
title: DKAN
subtitle: "Open Source Open Data Catalog"
# Base URL of site. It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
#baseurl: "http://localhost:8888" # the subpath of your site
#url: "http://luminousrubyist.github.io" # the base hostname & protocol for your site
baseurl: "https://getdkan.github.io/dkan-site"
cover: "cover.png"
logo: "logo.png"

# Build settings
markdown: kramdown

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."
